services:
  web:
    container_name: my-app
    build: .
    networks:
      - promNet
    ports:
      - 8080:80
    volumes:
      - ./log:/app/log
      - /etc/localtime:/etc/localtime:ro
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    networks:
      - promNet
    ports:
      - 9090:9090
    volumes:
      - ./config:/etc/prometheus
    command:
      - '--web.external-url=http://localhost:9090'
      - '--config.file=/etc/prometheus/prometheus.yml'
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager
    networks:
      - promNet
    ports:
      - 9093:9093
    volumes:
      - ./config/alertmanager:/etc/alertmanager
    command:
      - '--web.external-url=http://localhost:9093'
      - '--config.file=/etc/alertmanager/alertmanager.yml'
  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    networks:
      - promNet
    ports:
      - 3000:3000
networks:
  promNet:
    driver: bridge
    name: promNet
