global:
  evaluation_interval: 1s
  # https://pracucci.com/prometheus-understanding-the-delays-on-alerting.html

scrape_configs:
  - job_name: my_app
    scrape_interval: 5s
    static_configs:
      - targets:
        - web:80
        labels:
          app: my_app
rule_files:
  - alerting.rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
