global:
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'my_app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:2112']
        labels:
          app: 'my_app'
rule_files:
  - alerting.rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - alertmanager:9093
